Genesis block
Jumba/decentralized-mortgage-market pull request #26
Opened 2017-01-17 14:27 UTC by seuushi

Implement genesis block.

When a block is going to be added to the blockchain, it first checks whether the blockchain already contains blocks. If the blockchain does not contain any blocks, a genesis block will be added first. The genesis block is the very first block in the blockchain.

2017-01-17 14:55 UTC, Jumba commented on market/database/backends.py
> +            packet = encode(
Is it possible to actually create a `DatabaseBlock' that is the genesis block? And make a seperate function to generate the block and return it. Then you can just do `BlockChain.add_block(genesis)' right?

2017-01-17 14:55 UTC, Jumba commented on test/market/test_multichain.py
> +        genesis_block = self.db.get_by_public_key_and_sequence_number(str(self.member_bank), 0)
If you add the ability to create a genesis block separately you can check the "check_add_genesis_block" step, and just create a genesis block. Which you can use below to check if the new block that has been added automatically triggered the genesis block creation by checking if the previous block hash is equal to the genesis hash.

2017-01-17 16:41 UTC, seuushi commented on market/database/backends.py
> +            packet = encode(
Pushed the changes

2017-01-17 16:42 UTC, seuushi commented on test/market/test_multichain.py
> +        genesis_block = self.db.get_by_public_key_and_sequence_number(str(self.member_bank), 0)
Not sure what you meant with this. Please check the updated code.

2017-01-17 17:44 UTC, Jumba requested changes

2017-01-17 17:44 UTC, Jumba commented on market/database/backends.py
> +    def create_genesis_block(self, public_key_benefactor, public_key_beneficiary):
I think the genesis block should be equal over all clients.

2017-01-18 09:49 UTC, seuushi commented on market/database/backends.py
> +    def create_genesis_block(self, public_key_benefactor, public_key_beneficiary):
Review again please.

2017-01-18 09:57 UTC, Jumba approved these changes

2017-01-18 09:58 UTC, merged

2020-01-27 08:02 UTC, tanthanadon reviewed
Helllo